### ISSUE TITLE
TypeError: Cannot read property 'trackingCode' of undefined

### ISSUE THREAD

**Issue by narutohyc** [Rock-Candy-Tea/hexo-webpushr-notification#1]
作者，你好，感觉共享这个插件

我按照你的[Hexo浏览器定向推送文章更新](https://blog.ccknbc.cc/posts/hexo-webpushr-notification/)

配置了webpushrKey、webpushrAuthToken、trackingCode
同时注释掉了categories、segment

在github actions部署执行中报了一下的错，trackingCode我已经配置了，是还有什么地方吗

还是说在webpushr 网站那边需要填写或设置什么呢

``` js
(node:2275) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'sort' of undefined
    at Hexo.<anonymous> (/home/runner/work/hycBlog/hycBlog/node_modules/hexo-webpushr-notification/index.js:15:29)
    at Hexo.emit (events.js:326:22)
    at /home/runner/work/hycBlog/hycBlog/node_modules/hexo/lib/hexo/index.js:458:14
    at tryCatcher (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/promise.js:673:18)
    at MappingPromiseArray.PromiseArray._resolve (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/promise_array.js:127:19)
    at MappingPromiseArray._promiseFulfilled (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/map.js:108:18)
    at Promise._settlePromise (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/promise.js:609:26)
    at Promise._settlePromise0 (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
(node:2275) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2275) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
ERROR Render HTML failed: 404.html
TypeError: Cannot read property 'trackingCode' of undefined
    at Hexo.<anonymous> (/home/runner/work/hycBlog/hycBlog/node_modules/hexo-webpushr-notification/index.js:124:431)
    at Hexo.tryCatcher (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/method.js:15:34)
    at /home/runner/work/hycBlog/hycBlog/node_modules/hexo/lib/extend/filter.js:67:52
    at tryCatcher (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/reduce.js:166:18)
    at Object.gotAccum (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/reduce.js:155:25)
    at Object.tryCatcher (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
ERROR Render HTML failed: about/index.html
TypeError: Cannot read property 'trackingCode' of undefined
    at Hexo.<anonymous> (/home/runner/work/hycBlog/hycBlog/node_modules/hexo-webpushr-notification/index.js:124:431)
    at Hexo.tryCatcher (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/method.js:15:34)
    at /home/runner/work/hycBlog/hycBlog/node_modules/hexo/lib/extend/filter.js:67:52
    at tryCatcher (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/reduce.js:166:18)
    at Object.gotAccum (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/reduce.js:155:25)
    at Object.tryCatcher (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/promise.js:[547](https://github.com/hycBook/hycBlog/actions/runs/3335937397/jobs/5520487359#step:4:548):31)
    at Promise._settlePromise (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/runner/work/hycBlog/hycBlog/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
ERROR Render HTML failed: bangumis/index.html
TypeError: Cannot read property 'trackingCode' of undefined
```

**Comment by CCKNBC** [comment]
不太清楚为什么没有读取到这两个参数，我再看一下源码

**Comment by CCKNBC** [comment]
代码判断逻辑还是有漏洞

**Comment by CCKNBC** [comment]
如果你不需要这些功能，建议还是用原插件

**Comment by narutohyc** [comment]
我試了下原插件 也是這個錯誤

**Comment by narutohyc** [comment]
所以是代碼邏輯上的漏洞嗎  我也是but主題

**Comment by CCKNBC** [comment]
能否提供一下配置项
```yaml

```

**Comment by narutohyc** [comment]
這裏支持私信嗎

**Comment by narutohyc** [comment]
#   webpushrKey: "3cee2765f77cbf4f86e394f22cc1a91f" # 出于安全考虑，建议添加至系统环境变量，并注释掉此处配置
#   webpushrAuthToken: "60048" # 出于安全考虑，建议添加至系统环境变量，并注释掉此处配置

**Comment by CCKNBC** [comment]
照理来讲，应该没什么问题，这是我的配置可供参考 https://github.com/Rock-Candy-Tea/hexo-webpushr-notification#readme
